### ISSUE TITLE
Working sample?

### ISSUE THREAD

**Issue by matheusjardimb** [jzafrilla/AndroidImageHostpot#1]
It seems the sample provided doesn't have hotspots, isn't it? 

Do you have a newer version with working hotspots? 

thanks!

**Comment by fukemy** [comment]
shit library

**Comment by jzafrilla** [comment]
@fukemy it's not a library, it's an example. Checkout the results: https://play.google.com/store/apps/details?id=com.tfeditores.alhambra

![image](https://cloud.githubusercontent.com/assets/2435791/25422580/a0bf7d76-2a61-11e7-9ced-a3de27fab893.png)
